### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by coliff** [Reggionick/s3-deploy#208]
I just ran `npm run start` (after npm install) and got error:

```
> github-action-s3-deploy@4.0.0 start
> env-cmd node index.js

Error: Failed to find .env file at default paths: [./.env,./.env.js,./.env.json]
    at getEnvFile (C:\Users\coliff\Documents\GitHub\s3-deploy\node_modules\env-cmd\dist\get-env-vars.js:58:11)
    at async Object.EnvCmd (C:\Users\coliff\Documents\GitHub\s3-deploy\node_modules\env-cmd\dist\env-cmd.js:39:15)
    at async Object.CLI (C:\Users\coliff\Documents\GitHub\s3-deploy\node_modules\env-cmd\dist\env-cmd.js:19:16)
```

Any ideas? I'm using Node v18.19.1 on Windows 11.

**Comment by coliff** [comment]
@nabadeep25 - Could this be related to your merged PR?

**Comment by nabadeep25** [comment]
> @nabadeep25 - Could this be related to your merged PR?
@coliff 
No, I don't think so. I checkout to the commit before My PR got merged and I am getting the same error. Do you have env file at the root folder ? Because when I added a dummy .env file, error is gone.

**Comment by coliff** [comment]
thanks for the quick reply - I think it's fine then, I'll close this. :-)
