### ISSUE TITLE
Error: EACCES: permission denied, scandir '/boot/efi'

### ISSUE THREAD

**Issue by ArnauKokoro** [Reggionick/s3-deploy#37]
Hi, I would like to know exactly what this error means.

Is about any permission I do not have on S3?

I gave permissions AmazonS3FullAccess and CloudFrontFullAccess to that github user.

This is my config:

with:
          folder: /
          bucket: ***
          bucket-region: ***
          dist-id: ***
          invalidation: /*
          delete-removed: false
          no-cache: true
          private: false
          
Many thanks!!

```
Error: EACCES: permission denied, scandir '/boot/efi'
    at Object.readdirSync (fs.js:1043:3)
    at GlobSync._readdir (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:286:41)
    at GlobSync._readdirInGlobStar (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:265:20)
    at GlobSync._readdir (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:274:17)
    at GlobSync._processGlobStar (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:348:22)
    at GlobSync._process (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:128:10)
    at GlobSync._processGlobStar (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:381:10)
    at GlobSync._process (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:128:10)
    at GlobSync._processGlobStar (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:381:10)
    at GlobSync._process (/home/runner/.npm/_npx/1502/lib/node_modules/s3-deploy/node_modules/glob/sync.js:128:10)
```

**Comment by Reggionick** [comment]
Hi @ArnauKokoro, I think that you're trying to access to the root path of the disk `/` and not at the same path of the script `./`. (See the `folder` param)

**Comment by ArnauKokoro** [comment]
Hi @Reggionick, If I want to upload everything in the repo (repo root /) to the root (/) of the s3, what do I need to set on folder?
