### ISSUE TITLE
Uploads silently failing

### ISSUE THREAD

**Issue by NickLarsenNZ** [Reggionick/s3-deploy#38]
I've recently been receiving the following errors when uploading files:

```
/usr/local/bin/npx s3-deploy@1.4.0 ./** --bucket --region af-south-1 --cwd ./ --etag --gzip xml,html,htm,js,css,ttf,otf,svg,txt --deleteRemoved --private
Deploying files: [
  '.',
  './asset-manifest.json',
  './assets',
  './assets/images',
  './assets/images/flags',

...

  './assets/images/flags/GT.svg',
  ... 212 more items
]
► Target S3 bucket: true (af-south-1 region)
► Gzip: [
  'xml', 'html',
  'htm', 'js',
  'css', 'ttf',
  'otf', 'svg',
  'txt'
]
► E-Tag: true
► Private: true
► Deleting removed files
TypeError: str.indexOf is not a function
    at Object.validateARN [as validate] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/util.js:1008:25)
    at Object.isArnInParam (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3util.js:12:25)
    at features.constructor.setupRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3.js:144:56)
    at features.constructor.addAllRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:276:10)
    at features.constructor.makeRequest (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.<computed> [as headObject] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:685:23)
    at /home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:188:12
    at new Promise (<anonymous>)
    at sync (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:178:10)
    at _callee2$ (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:303:18)
TypeError: str.indexOf is not a function
    at Object.validateARN [as validate] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/util.js:1008:25)
    at Object.isArnInParam (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3util.js:12:25)
    at features.constructor.setupRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3.js:144:56)
    at features.constructor.addAllRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:276:10)
    at features.constructor.makeRequest (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.<computed> [as headObject] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:685:23)
    at /home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:188:12
    at new Promise (<anonymous>)
    at sync (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:178:10)
    at _callee2$ (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:303:18)
TypeError: str.indexOf is not a function
    at Object.validateARN [as validate] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/util.js:1008:25)
    at Object.isArnInParam (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3util.js:12:25)
    at features.constructor.setupRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3.js:144:56)
    at features.constructor.addAllRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:276:10)
    at features.constructor.makeRequest (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.<computed> [as headObject] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:685:23)
    at /home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:188:12
    at new Promise (<anonymous>)
    at sync (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:178:10)
    at _callee2$ (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:303:18)

...

TypeError: str.indexOf is not a function
    at Object.validateARN [as validate] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/util.js:1008:25)
    at Object.isArnInParam (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3util.js:12:25)
    at features.constructor.setupRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3.js:144:56)
    at features.constructor.addAllRequestListeners (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:276:10)
    at features.constructor.makeRequest (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.<computed> [as listObjectsV2] (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/service.js:685:23)
    at /home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:88:12
    at new Promise (<anonymous>)
    at listAllKeys (/home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:87:10)
    at /home/runner/.npm/_npx/1880/lib/node_modules/s3-deploy/dist/deploy.js:111:5
Upload finished
```

_3489 lines of output_

The job finishes successfully, but new files are missing in my S3 bucket.

My workflow is set up like so:

```yml
    - uses: reggionick/s3-deploy@v3
      with:
        folder: build
        bucket: ${{ needs.terraform_dev.outputs.bucket }}
        dist-id: ${{ needs.terraform_dev.outputs.distribution_id }}
        invalidation: /
        delete-removed: true
        bucket-region: ${{ needs.terraform_apply_dev.outputs.bucket_region }}
        private: true
```

**Comment by sebastiankutschbach** [comment]
seems to be the related to #35

**Comment by bfintal** [comment]
I encountered this error when I upgraded to npm version 8.*. It was because the `bucket` argument I was passing was invalid.

I used an environment variable in my package.json to reference my bucket & cloudfront configuration as `$npm_package_cloudfront_bucket`, this worked in npm < 7. But in newer versions, the environment variable now needs to be inside the `config` property, so moving to `$npm_package_config_cloudfront_bucket` made it work for me.

**Comment by hikkoiri** [comment]
Same experience here. I forgot to specify the S3_Bucket secret in `bucket: ${{ secrets.S3_BUCKET }}` and was wondering why the deployment seemed to be okay (while it was obviously not working as expected). It would be nice to have a warning or even an error indicating that required parameters are missing.

**Comment by Reggionick** [comment]
> seems to be the related to #35

Duplicate
