### ISSUE TITLE
access denied with valid API key

### ISSUE THREAD

**Issue by yangcheng** [Reggionick/s3-deploy#7]
```
File Matches, skipped favicon.ico
File Matches, skipped manifest.json
File Matches, skipped logo512.png
File Matches, skipped static/js/runtime-main.5a93116f.js.map
File Matches, skipped logo192.png
Upload error: AccessDenied: Access Denied
    at Request.extractError (/home/runner/.npm/_npx/2757/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (/home/runner/.npm/_npx/2757/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/.npm/_npx/2757/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/.npm/_npx/2757/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/runner/.npm/_npx/2757/lib/node_modules/s3-deploy/node_modules/aws-sdk/lib/request.js:22:10)
```

I double checked the  same API key has S3 PUT and I can do upload from my computer using the same key, however, the github action run generate the error message. 
Where should I start to debug?

**Comment by Reggionick** [comment]
Hi @yangcheng,

you could try running the [s3-deploy](https://github.com/import-io/s3-deploy#readme) script directly on your machine with this key to see if works.

Let me know!

**Comment by yangcheng** [comment]
thanks! by using s3-deploy script I found some issue in the policy. now it works

**Comment by seamuslowry** [comment]
@yangcheng care to share what the issue was? I have a user with full s3 and full cloudfront access. What else does it need?

**Comment by yangcheng** [comment]
for me it print a clear message and I noticed it's an action missing (I forget which one)

**Comment by vhd-jake** [comment]
I'm having this same error when running in workflow, but when i run this scrip on my machine it just exits after the message `Invalidation XXXXXXXX is in progress...` with no error, any ides?
