### ISSUE TITLE
The build doesn't fail on access denied error

### ISSUE THREAD

**Issue by nikita-volkov** [Reggionick/s3-deploy#76]
Here's a snippet from the build log. The build succeeds despite the error.

```
...
Unexpected error: (Forbidden) null, aborting upload for assets/img/images/ris.png
Upload finished
AccessDenied: Access Denied
    at Request.extractError (/home/runner/.npm/_npx/55[94](https://github.com/EdgeNode/frontend/runs/6738611211?check_suite_focus=true#step:6:95)7e5ced8dc5f0/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'AccessDenied',
...
```

**Comment by daniele-sarnari-blinkoo** [comment]
Same here, btw what causes this error?

**Comment by b-d055** [comment]
I was having a very similar issue, uploading a static site:
```
Unexpected error: (Forbidden) null, aborting upload for index.html
Unexpected error: (Forbidden) null, aborting upload for news.html
Unexpected error: (Forbidden) null, aborting upload for robots.txt
...
```

The issue was fixed for my by making sure I had the right permission on both the bucket and objects. #41 is a good example.

**Comment by schw4rzlicht** [comment]
This should fail the pipeline imo.
