### ISSUE TITLE
TypeError: region.split is not a function

### ISSUE THREAD

**Issue by Blumed** [Reggionick/s3-deploy#92]
I getting this error when running the example code in the READ.ME

```
TypeError: region.split is not a function
    at generateRegionPrefix (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/region_config.js:6:22)
    at derivedKeys (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/region_config.js:13:22)
    at Object.configureEndpoint (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/region_config.js:38:14)
    at features.constructor.initialize (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/service.js:72:45)
    at features.constructor.Service [as constructor] (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/service.js:59:10)
    at features.constructor (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/util.js:637:24)
    at new features.constructor (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/util.js:637:24)
    at features.constructor.Service [as constructor] (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/service.js:50:17)
    at new features.constructor (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/aws-sdk/lib/util.js:637:24)
    at _callee3$ (/home/runner/.npm/_npx/55947e5ced8dc5f0/node_modules/s3-deploy/dist/deploy.js:406:22)****
```

I pulled your repo down and nothing is jumping out as an obvious fix. All of my secrets match the pattern you created in the example.

The error says region and I double checked to make sure my region secret was right and it is. I also purposefully made it incorrect that didn't seem to make a difference.

Any idea what might be happening here?

**Comment by jmckie94** [comment]
@Blumed I am also getting the same error as you.

**Comment by dmolik** [comment]
same, self-hosted runners, could use some help

**Comment by dmolik** [comment]
Turns out I had a misspelling.

**Comment by dekatron** [comment]
@Blumed I got this exact same error but it was because I was missing the `S3_BUCKET_REGION` secret, I had `S3_BUCKET` which is very similarly named. I think when I tried to create `S3_BUCKET_REGION` it gave me an error message about special characters and when I checked I misread `S3_BUCKET` seems to work now I've added it.

**Comment by Blumed** [comment]
@dekatron I had that unfortunately. Thanks for the suggestion. Going to reset everything and see if there was something with a space at the end of a variable or something.

**Comment by Blumed** [comment]
I was able to get it to work if I don't use github secret for s3 bucket region. Not sure why. I have quadruple checked it but for whatever reason it just doesn't work with github.
